// 角色数据定义
const characters = [
  {
    id: "emberstar",
    name: "星荧",
    alias: "Emberstar",
    age: "10 (?)",
    gender: "无性",
    height: "145cm (超频状态165cm)",
    weight: "24kg",
    race: "人 (?)",
    birthday: "1月60日",
    divineEye: "星尘之眼: 四重权能『始源』『终末』『虚无』『真我』",
    favoriteFood: "蜂蜜蛋糕, 昼夜茶(冰萃/冷萃), 马卡龙(蓝紫色系和白色)",
    personality: "外表安静内敛，带有轻度社恐，但内心坚韧执着。秉持积极虚无主义，对善恶判断极为敏锐，虽心怀慈悲却绝不愚善。",
    soulNature: "真我",
    location: "净土",
    description: "作为最后被创造的『神之子嗣』，星荧是『始源』与『终末』双神自裁前留下的终极造物。其存在本身即是矛盾：同时承载创造与毁灭的权能，四重权能的性质和解析充满矛盾性。神之眼永远保持开启状态，体内魔法能量上限被始源之神刻意限制(但有99.9%的减耗)。成功突破虚无困境，觉醒独有『真我』权能，同时也是『Emberstar OS』最高权限持有者。",
    motto: "即便一切都是虚无，我也会去寻找那一抹色彩",
    status: "alive",
    avatar: '/assets/avatar/emberstar.jpg'
  },
  {
    id: "lumirise",
    name: "璃梦",
    alias: "Lumirise",
    age: "16",
    gender: "女",
    height: "159cm",
    weight: "52kg",
    race: "人 (?)",
    birthday: "4月30日",
    divineEye: "烬笼之瞳: 控制瘟疫",
    favoriteFood: "昼夜茶(热萃，加双倍蜂蜜), 草莓奶油三明治, 枫糖松饼",
    personality: "本性温柔善良，但因长期受控而显得阴郁沉默。对自身罪孽有深刻认知，赎罪意志极为坚定。恢复自由后逐渐展现出少女应有的活泼一面，对星荧抱有近乎偏执的保护欲(愧疚感转化)。",
    soulNature: "笼中之鸟，终将飞翔",
    location: "净土",
    description: "被人畏惧地称作『瘟疫魔女』，但真实愿望只是想做普通女孩。同时具备部分死亡之神和毁灭之神的权能。在被控制期间犯下诸多罪孽，虽深知难以被原谅，仍坚持用修复后的能力帮助他人赎罪。在余娜媞思的审判中，因星荧的证言和自身悔过表现获得宽大处理。",
    motto: "笼中的羽翼终将划破长夜------以新生为刃，斩断枷锁。",
    status: "alive",
    avatar: '/assets/avatar/lumirise.png'
  },
  {
    id: "cielune",
    name: "希月",
    alias: "Cielune",
    age: "17",
    gender: "女",
    height: "164cm",
    weight: "52kg",
    race: "人 (?)",
    birthday: "5月1日",
    divineEye: "死生轮瞳: 创生与凋零",
    favoriteFood: "昼夜茶(加入自采的蒲公英), 苹果派, 可丽露",
    personality: "天性善良温柔，但绝非盲目慈悲。对生命怀有至高敬意，但对恶意绝不姑息。作为姐姐对星荧格外关照，常为其调解矛盾。",
    soulNature: "死生天平",
    location: "净土",
    description: "由生命之神-希塔娜创造的『神之子嗣』，虽非星荧血亲却情同手足。肩负维系生死平衡的职责，但不受任何神明操控。能同时感知方圆五公里内所有生命的诞生与消亡。",
    motto: "生命的天平无需倾斜，凋零与绽放皆是永恒的回响。",
    status: "alive",
    avatar: '/assets/avatar/cielune.png'
  },
  {
    id: "seren",
    name: "久夜",
    alias: "Seren",
    age: "1",
    gender: "无性",
    height: "142cm (超频状态同星荧一样)",
    weight: "42kg",
    race: "人 (?)",
    birthday: "11月60日",
    divineEye: "虚烬双曈: 对应星荧的『虚无』和『真我』和希月的『生命·创生/凋零』",
    favoriteFood: "昼夜茶(模仿星荧的冷/冰萃方式), 焦糖布丁, 冰糖葫芦",
    personality: "轻度社恐，性格温和但保有坚定意志，圣母但不愚善，对世界抱有极少的偏见。因承载戚紫涵的灵魂，偶尔会流露出不属于自己的情感片段，但始终尊重这份意识的独立性。",
    soulNature: "真我",
    location: "净土",
    description: "代号 ST-0715的实验体，是星荧在探索「生命的第一因」时意外创造的唯一成功人偶。与其他实验体不同，久夜并非依靠技术或魔法强行赋予意识，而是因戚紫涵的灵魂碎片作为\"媒介\"，在虚无与存在的夹缝中自发诞生了\"自我\"------这是连星荧都未能预料的奇迹。",
    motto: "她的愿望，我的选择------两颗心跳同频，却跳动着独属于'我'的旋律。",
    status: "alive",
    avatar: '/assets/avatar/seren.jpg'
  },
  {
    id: "selaine",
    name: "陌叶",
    alias: "Selaine",
    age: "14",
    gender: "女",
    height: "143cm",
    weight: "40kg",
    race: "人",
    birthday: "7月15日",
    divineEye: "无",
    favoriteFood: "烤面包片配果酱, 番茄土豆浓汤, 薄荷糖",
    personality: "在经历父母双亡、妹妹被献祭等苦难后仍保持善良本性。有着超越年龄的成熟与坚韧。对妹妹陌心保护欲极强，已形成轻度ptsd反应。对星荧抱有深深的感激之情。",
    soulNature: "荆棘守护",
    location: "净土",
    description: "原为贵族大小姐(仁尹)的普通朋友，在父母去世后与妹妹陌心相依为命。妹妹被村民献祭给邪神后，在绝望之际遇见星荧，同意将濒死的妹妹改造为类人偶存在。现与妹妹一起在净土生活。",
    motto: "即使世界布满荆棘，我也会为身后之人踏出一条路。",
    status: "alive",
    avatar: "/assets/avatar/selaine.png"
  },
  {
    id: "qizixuan",
    name: "戚紫萱",
    alias: "Qi Zixuan",
    age: "19",
    gender: "女",
    height: "179cm",
    weight: "55kg",
    race: "血族",
    birthday: "10月31日",
    divineEye: "无",
    favoriteFood: "小笼包, 龙须糖, 茉莉花茶",
    personality: "表象：冷峻寡言，习惯用讽刺与疏离掩饰内心的自我憎恨。内在：因亲手杀死妹妹(戚紫涵)而深陷悔恨，但从未真正堕落，仍以人类的标准约束自己。厌恶阳光(神经性不适，非物理伤害)，却会强迫自己忍受，作为对过去的惩罚。对善意不知所措，常以毒舌回应，但暗地里会默默保护弱者。",
    soulNature: "双生残烬",
    location: "净土(目前时间线已死)",
    description: "原为人类，在一所教堂实验室被神父转化为吸血鬼。虽未失去人性，却因杀害妹妹的罪孽不断自我否定。被星荧与久夜(体内有紫涵灵魂)救赎后，折断象征吸血鬼身份的十字架项链，随众人前往净土。在净土定居后，主动担任夜间巡逻，以血族之力守护他人，试图弥补罪孽。",
    motto: "月光下的玫瑰终将凋零------但刺尖上悬挂的，永远是我未能流尽的泪水。",
    status: "deceased",
    avatar: "/assets/avatar/qizixuan.jpg"
  },
  {
    id: "lumina",
    name: "陌心",
    alias: "Lumina",
    age: "11",
    gender: "女",
    height: "139cm",
    weight: "24kg",
    race: "人(后因献祭事件影响人偶化)",
    birthday: "12月1日",
    divineEye: "无",
    favoriteFood: "热牛奶, 动物饼干, 蜂蜜酸奶",
    personality: "天真善良，对姐姐陌叶极度依赖。因献祭事件导致人偶化，但保留大部分人类特征。体温较常人低1.5℃，但怀抱玩偶时会逐渐回升。异常厌恶钟表声(献祭仪式关联记忆)。",
    soulNature: "霜荆之心",
    location: "净土",
    description: "被村民献祭给邪神的牺牲品，濒死时由星荧改造为类人偶存在。保留人类基本生理需求，但具有部分人偶特性。左肩留有献祭仪式的荆棘状烙印。因为全身上下的经脉被那些村民挑断，星荧用了很久的时间才勉强将那些经脉重新缝合好。",
    motto: "冰冷的皮肤下，依然是温暖的血肉；冰冷的仪式之后，我仍能感受姐姐的拥抱。",
    status: "alive",
    avatar: "/assets/avatar/lumina.png"
  },
  {
    id: "etherealvelos",
    name: "艾瑟尔·维洛斯",
    alias: "Ethereal Velos",
    age: "未知(外表为25岁)",
    gender: "女",
    height: "181cm",
    weight: "61kg",
    race: "人 (?)",
    birthday: "8月60日",
    divineEye: "幻寐之镜: 可读取、修改并裁定所有生物的梦境",
    favoriteFood: "伯爵茶配司康, 可露丽, 蝶豆花冻",
    personality: "对梦境中的异常极度敏感，能瞬间识别潜意识的伪装。现实世界中略显疏离，常无意识使用梦境逻辑思考。对星荧等\"同辈\"神之子嗣会表现出罕见的耐心。",
    soulNature: "梦蝶",
    location: "梦境世界",
    description: "始源之神创造的梦境管理者，长期居于梦境夹缝中的「回廊庭园」。可自由调整梦境中的形态(曾以男性形象引导迷途者)，现实世界则固定为女性形态。",
    motto: "真实与幻梦的界限，不过是我书页的正反两面。",
    status: "alive",
    avatar: "/assets/avatar/etherealvelos.jpg"
  },
  {
    id: "reyna",
    name: "仁尹",
    alias: "Reyna/Rill",
    age: "18",
    gender: "女",
    height: "175cm",
    weight: "60kg",
    race: "人",
    birthday: "3月20日",
    divineEye: "无",
    favoriteFood: "大吉岭红茶, 咸牛肉三明治, 樱桃派",
    personality: "本质善良但口是心非，所有温柔都藏在毒舌之下。右眼受伤后产生的阴郁气质与本性形成强烈反差。对陌叶姐妹有种笨拙的保护欲(常借口顺路护送)。",
    soulNature: "铁棘之华",
    location: "维多亚瑟自管区(属迪亚妲斯)",
    description: "维多亚瑟家族第七十代大小姐，因厌恶贵族虚伪作风而亲近平民。刺客袭击事件导致右眼重伤后，被家族视为\"不祥之人\"，反而获得更多自由行动空间。",
    motto: "铁棘丛中绽放的花，无需向谁证明她的锋芒。",
    status: "alive",
    avatar: "/assets/avatar/reyna.png"
  },
  {
    id: "lumiere",
    name: "璃依",
    alias: "Lumiere",
    age: "19",
    gender: "女",
    height: "175cm",
    weight: "60kg",
    race: "人",
    birthday: "6月60日",
    divineEye: "无",
    favoriteFood: "可颂面包, 肉桂苹果卷, 薰衣草茶",
    personality: "表面温和隐忍，内心充满对真相的渴望，偶尔流露孤独感。因失明导致对声音异常敏感，习惯通过语气和脚步声判断他人情绪。对\"瘟疫魔女\"的传闻抱有复杂矛盾心理，既憎恨又隐约怀疑背后另有隐情。",
    soulNature: "盲眼之烛",
    location: "净土",
    description: "曾经因为瘟疫魔女带来的灾难让她失去了父母，后面因为一场大火夺走了她的双眼，只能依靠自身的听觉和盲杖辅助生活。目前在一家面包店干着服务员工作，虽然眼睛看不见东西，但后面根据练习也能准确分辨得出面包的种类了。",
    motto: "黑暗并非虚无------它只是光明的另一种语言。",
    status: "alive",
    avatar: "/assets/avatar/lumiere.jpg"
  },
  {
    id: "qiyubai",
    name: "戚羽白",
    alias: "Qi Yubai",
    age: "12",
    gender: "女",
    height: "152cm",
    weight: "49kg",
    race: "亚人(猫耳亚种)",
    birthday: "2月28日",
    divineEye: "无",
    favoriteFood: "清蒸鱼, 温热的羊奶, 小鱼干饼干",
    personality: "猫般的警觉与脆弱：对突然的声响会炸毛(耳朵竖直、尾巴蓬松)，尤其是金属碰撞声(联想镣铐)。被触碰时可能无意识抓咬对方，但事后会蜷缩起来发抖。矛盾的生存本能：厌恶人类却依赖施舍，讨好主人后又会躲在角落干呕。对戚紫萱的记忆产生\"自我憎恨\"。",
    soulNature: "残烛余烬",
    location: "净土",
    description: "戚紫萱的转世，亚人种族，亚人的地位较为低下，携带了部分前世记忆，上一代主人对他做了很多恶事，过分点在于随后还让地痞流氓对她行了污浊之事，导致患上了比较严重的PTSD。",
    motto: "猫有九条命......可为什么我只觉得疼？",
    status: "alive",
    avatar: "/assets/avatar/qiyubai.png"
  },
  {
    id: "vanya",
    name: "银铃",
    alias: "Vanya",
    age: "19",
    gender: "女",
    height: "174cm",
    weight: "54kg",
    race: "人",
    birthday: "9月59日",
    divineEye: "无",
    favoriteFood: "卡莉斯塔炖菜, 果酱三明治, 昼夜茶+牛奶的\"奶茶\"",
    personality: "矛盾的双面性：作为教会圣女，对外维持温柔虔诚的假象，习惯用微笑掩盖痛苦。语言风格刻意轻快，但偶尔会无意识流露疲惫的颤音。因灵魂被反复侵蚀，逐渐丧失对自我身份的认知，甚至怀疑\"银铃\"是否只是容器的代号。对神明与教会抱有隐秘的恨意，却因长期精神控制无法反抗，形成自我厌恶。",
    soulNature: "残烛余烬",
    location: "卡莉斯塔(在《卡莉斯塔》剧情之后，与星荧同行)",
    description: "被卡莉斯塔教会选中的第13任\"圣女\"，拥有特殊体质------能成为神明降临的容器，代价是灵魂被反复撕裂。历任圣女皆因灵魂枯竭而亡，唯独银铃在彻底崩溃前，被星荧以『生命琼露』与『真我』权能强行挽留。如今，她带着残破的灵魂与模糊的记忆定居净土，成为\"笼中鸟破笼\"的又一象征。",
    motto: "我本可忍受黑暗......如果\"她\"(星荧和久夜)不曾带着光闯进来。",
    status: "alive",
    avatar: "/assets/avatar/vanya.jpg"
  },
  {
    id: "tanjiu",
    name: "檀玖",
    alias: "Tan Jiu",
    age: "未知",
    gender: "男",
    height: "130cm",
    weight: "28kg",
    race: "人 (?)",
    birthday: "4月25日",
    divineEye: "无",
    favoriteFood: "紫薯, 葡萄(尤其喜欢冰镇后的口感), 昼夜茶(偏好清淡口味)",
    personality: "外表开朗活泼，言行中常带懒散感，但面对委托时会展现出极高的专注力。秉持个人主义，\"并非自私，而是对我的尊重\"。对孩童与弱者有天然保护欲，会默默解决他人困境后装作无事发生。",
    soulNature: "暗光同尘",
    location: "净土",
    description: "来历成谜的流浪者，虽掌控黑暗权能却厌恶滥用力量，常以孩童外貌降低他人警惕。与星荧等人相遇后，选择留在净土充当邻居。",
    motto: "黑暗亦可温柔------你看，连影子都舍不得踩疼花朵。",
    status: "alive",
    avatar: "/assets/avatar/Tanjiu.png"
  },
  {
    id: "anahita",
    name: "余娜媞思",
    alias: "Anahita / 阿娜希塔",
    age: "12000岁(人类时期约12岁)",
    gender: "女",
    height: "178cm(神形态)/140cm(人类时期记忆形象)",
    weight: "62kg(神形态)",
    race: "神明", // 修复：添加race属性
    birthday: "未知(以升格日为纪念日：始源历2500年·流水之月第1日)",
    divineEye: "裁决之瞳",
    favoriteFood: "野生蜂蜜水, 星荧烤的蜂蜜蛋糕, 冰镇昼夜茶(加双份浆果)",
    personality: "表象：冷漠严肃，惜字如金，规则大于一切。对星荧看似严苛，实则全神界最溺爱她的存在。内在：怀旧者，秘密收藏人类时期的陶片、流水纹织物。守护者，为庇护所爱之人可公然违背神律。笨拙的温柔，以\"裁决公文批注\"传递关怀。",
    soulNature: "天平之韧",
    location: "神界",
    description: "本质：\"披神袍之人\"------虽为神明，内核始终保留人类时期的共情与韧性。人类时期(阿娜希塔)：生于距今约2500万年的原始流域文明，名字\"阿娜希塔\"意为\"纯洁之水\"。身患不治之症，濒死时被始源与终末之神发现(经过她父母同意的)，带入神界升格为见习天使。因意志坚定被选为裁决之神候选，历经漫长试炼后正式继任。",
    motto: "从来没有真正公正的裁决，也从来没有真正的正义，这些也只是行走于规则的蛀虫而已",
    status: "alive",
    avatar: "/assets/avatar/anahita.png"
  },
  {
    id: "emberstar_stardust",
  name: "星荧「星尘之神」",
  alias: "Emberstar, The Stardust Divinity",
  age: "16 (拒绝使用神明的年龄)",
  gender: "无性",
  height: "165cm ",
  weight: "42kg (还是原本的身体)",
  race: "人（拒绝神明的身份）",
  birthday: "1月6日",
  divineEye: "星尘之眼（依旧如此）",
  favoriteFood: "记忆中蜂蜜蛋糕的味道, 冷却的昼夜茶余温, 已不复存在的马卡龙色彩",
  personality: "外表疏离宁静，带有神性的绝对理性（其实根本就没有神性都是装的），但内核是固结为人性的巨大悲伤。以神格承载所有失落时间线的记忆与羁绊，虽见证无数终末却拒绝成为无情的神明。对『星荧』这个名字抱有近乎偏执的坚守。",
  soulNature: "真我（依旧如此）",
  location: "时间象限的交界处/净土的每个窗口外",
  description: "来自失落时间线的终极幸存者。在原时间线中被命运织者以所有同伴的存在为要挟，被迫登神后却目睹一切被抹除。巨大的创伤性人性压倒神性，固结为『星荧』的残响。如今以『神明』身份存在于一切开始与结束的交点，既是神明也是囚徒——神格让她不朽，人性让她永远疼痛。她不是星荧的『神化』，而是星荧的『遗骸』，是那个差点忘记自己名字、最终刻下所有名字的孤独存在。她守护所有平行时空的净土，因为那是她唯一记得的『家』的模样。",
  motto: "「我守望一切终末，只为确保无人再需成为我。」",
  status: "alive", 
    avatar: '/assets/avatar/emberstar「stardust」.jpg',
  }
];


export function queryCharacters(query) {
  return characters.filter(character =>
    character.name.includes(query) ||
    character.alias.includes(query) ||
    character.description.includes(query)
  );
}

// 获取所有角色
export function getAllCharacters() {
  return characters;
}

// 根据ID获取角色
export function getCharacterById(id) {
  return characters.find(character => character.id === id);
}
